### ISSUE TITLE
"Matrix was suspicious" assertion error when launching with ?ea

### ISSUE THREAD

**Issue by samreid** [phetsims/sugar-and-salt-solutions#5] opened 2015-01-06 12:24 UTC
I tried running the simulation with ?ea to enable assertions and it failed to start, reporting a "matrix was suspicious" assertion error.

**Comment by samreid** [comment] 2015-01-06 12:28
It is generally advisable to run with ?ea frequently during development, though sometimes it will interfere with performance testing.

**Comment by jonathanolson** [comment] 2015-02-04 23:41
More notes:

```
Error: Assertion failed: Matrix was suspicious
    at window.assertions.assertFunction (http://localhost/phet/git/assert/js/assert.js:22:13)
    at Transform3.setMatrix (http://localhost/phet/git/dot/js/Transform3.js?1423091571269:40:32)
    at Transform3.prependTranslation (http://localhost/phet/git/dot/js/Transform3.js?1423091571269:76:12)
    at Text.extend.prependTranslation (http://localhost/phet/git/scenery/js/nodes/Node.js?1423091571269:1246:23)
    at Text.extend.translate (http://localhost/phet/git/scenery/js/nodes/Node.js?1423091571269:1090:16)
    at Text.extend.setX (http://localhost/phet/git/scenery/js/nodes/Node.js?1423091571269:1157:12)
    at Text.x (http://localhost/phet/git/scenery/js/nodes/Node.js?1423091571269:2256:27)
    at SaltShakerNode.inherit.updateTransform (http://localhost/phet/git/sugar-and-salt-solutions/js/common/view/DispenserNode.js?1423091571269:102:24)
    at http://localhost/phet/git/sugar-and-salt-solutions/js/common/view/DispenserNode.js?1423091571269:71:16
    at new Multilink (http://localhost/phet/git/axon/js/Multilink.js?1423091571269:48:16)
```

The transform matrix trying to be applied:
```
6.123233995736766e-17 -1 -Infinity
1 6.123233995736766e-17 0
0 0 1
```

Caused by DispenserNode's imageNode being an empty Node (empty bounds), and fails line 102 of DispenserNode.

**Comment by veillette** [comment] 2018-03-20 14:20
No longer able to reproduce this assertion. Closing.

**Closed by veillette** 2018-03-20 14:20 UTC
Labels: type:bug
