### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/sugar-and-salt-solutions#10] opened 2015-03-08 17:58 UTC
Examples of anti pattern:

SugarAndSaltSharedProperties: sizeScale: new Property( 1.0 )
Dispenser: thisDispenser.enabled = new Property( false );
Dispenser:  thisDispenser.angle = new Property( angle );
Dispenser: thisDispenser.center = new Property( new Vector2( x, y ) );
SugarAndSaltSolutionMode: thisModel.dispenserType = new Property( DispenserType.SALT );

**Comment by veillette** [comment] 2018-03-20 14:40
Closing this issue since it is a duplicate of #8

**Closed by veillette** 2018-03-20 14:40 UTC
